-- MySQL Script generated by MySQL Workbench
-- Fri Jan 16 11:43:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MissClasse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MissClasse` ;

-- -----------------------------------------------------
-- Schema MissClasse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MissClasse` DEFAULT CHARACTER SET utf8 ;
USE `MissClasse` ;

-- -----------------------------------------------------
-- Table `MissClasse`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Lastname` VARCHAR(30) NOT NULL,
  `Firstname` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Acronyme` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Acronyme_UNIQUE` (`Acronyme` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Classes` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name_year` VARCHAR(30) NOT NULL,
  `Salle` VARCHAR(30) NOT NULL,
  `Teachers_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_year_UNIQUE` (`Name_year` ASC) VISIBLE,
  INDEX `fk_Classes_Teachers1_idx` (`Teachers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Classes_Teachers1`
    FOREIGN KEY (`Teachers_id`)
    REFERENCES `MissClasse`.`Teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Projects` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Name_groupe` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_groupe_UNIQUE` (`Name_groupe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Students` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Lastname` VARCHAR(30) NOT NULL,
  `Firstname` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  `Classes_id` INT NULL,
  `Projects_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Students_Classes_idx` (`Classes_id` ASC) VISIBLE,
  INDEX `fk_Students_Projects1_idx` (`Projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Classes`
    FOREIGN KEY (`Classes_id`)
    REFERENCES `MissClasse`.`Classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Projects1`
    FOREIGN KEY (`Projects_id`)
    REFERENCES `MissClasse`.`Projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Hours` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Hours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Days` VARCHAR(15) NOT NULL,
  `Date` DATE NOT NULL,
  `Period` DECIMAL(10) NOT NULL,
  `Begin` TIME NOT NULL,
  `End` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Absences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Absences` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Absences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(15) NOT NULL,
  `JustifiedRuling` TINYINT NULL,
  `Pattern` VARCHAR(35) NULL,
  `Hours_id` INT NOT NULL,
  `Students_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Absences_Hours1_idx` (`Hours_id` ASC) VISIBLE,
  INDEX `fk_Absences_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_Absences_Hours1`
    FOREIGN KEY (`Hours_id`)
    REFERENCES `MissClasse`.`Hours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Absences_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `MissClasse`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Projects_has_Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Projects_has_Teachers` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Projects_has_Teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Projects_id` INT NOT NULL,
  `Teachers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Projects_id`, `Teachers_id`),
  INDEX `fk_Projects_has_Teachers_Teachers1_idx` (`Teachers_id` ASC) VISIBLE,
  INDEX `fk_Projects_has_Teachers_Projects1_idx` (`Projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_Projects_has_Teachers_Projects1`
    FOREIGN KEY (`Projects_id`)
    REFERENCES `MissClasse`.`Projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_has_Teachers_Teachers1`
    FOREIGN KEY (`Teachers_id`)
    REFERENCES `MissClasse`.`Teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MissClasse`.`Classes_has_Hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MissClasse`.`Classes_has_Hours` ;

CREATE TABLE IF NOT EXISTS `MissClasse`.`Classes_has_Hours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Classes_id` INT NOT NULL,
  `Hours_id` INT NOT NULL,
  `Is_active` TINYINT NULL,
  PRIMARY KEY (`id`, `Classes_id`, `Hours_id`),
  INDEX `fk_Classes_has_Hours_Hours1_idx` (`Hours_id` ASC) VISIBLE,
  INDEX `fk_Classes_has_Hours_Classes1_idx` (`Classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Classes_has_Hours_Classes1`
    FOREIGN KEY (`Classes_id`)
    REFERENCES `MissClasse`.`Classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classes_has_Hours_Hours1`
    FOREIGN KEY (`Hours_id`)
    REFERENCES `MissClasse`.`Hours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
